"""empty message

Revision ID: 120410fe3365
Revises: 725a912b3833
Create Date: 2022-04-15 22:44:36.783265

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '120410fe3365'
down_revision = '725a912b3833'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('word') as batch_op:
        batch_op.drop_column('test')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('word', sa.Column('test', sa.VARCHAR(length=140), nullable=True))
    # ### end Alembic commands ###
