"""empty message

Revision ID: 20eb50c80b7a
Revises: 120410fe3365
Create Date: 2022-04-15 23:02:55.964924

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '20eb50c80b7a'
down_revision = '120410fe3365'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('word', sa.Column('test', sa.String(length=140), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('word', 'test')
    # ### end Alembic commands ###
