"""empty message

Revision ID: 570ead37623c
Revises: 0c8d7ec88718
Create Date: 2022-04-15 23:06:16.234070

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '570ead37623c'
down_revision = '0c8d7ec88718'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('word') as batch_op:
        batch_op.drop_column('translation')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('word', sa.Column('translation', sa.VARCHAR(length=140), nullable=True))
    # ### end Alembic commands ###
