"""empty message

Revision ID: 89f8b997cb4d
Revises: f32072670f71
Create Date: 2022-04-16 01:02:19.302994

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '89f8b997cb4d'
down_revision = 'f32072670f71'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('word') as batch_op:
        batch_op.drop_column('translation')
        batch_op.add_column(sa.Column('meaning', sa.String(length=240), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('word', sa.Column('translation', sa.VARCHAR(length=140), nullable=True))
    op.drop_column('word', 'meaning')
    # ### end Alembic commands ###
